<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Authentication</title>
	<?php require __DIR__ . '/parts/generalStyleLinks.phtml' ?>
    <link href="../src/styles/auth.page.css" rel="stylesheet">
    <script src="../src/scripts/auth.page.js" type="module" defer></script>
</head>
<body>
    <?php require __DIR__ . '/parts/noScript.phtml' ?>
    <main>
        <div>
            <h1 class="sign-method-heading">Sign In</h1>
            <div class="tabs-wrapper" data-active="0">
                <div class="tabs-panel">
                    <div class="tabs-panel-controls">
                        <div data-control="0">Sign In</div>
                        <div data-control="1">Sign Up</div>
                    </div>
                    <div class="tabs-line">
                        <div class="tabs-line-inner"></div>
                    </div>
                </div>
                <div class="tabs">
                    <form id="signin" data-tab="0" method="post">
                        <div class="input_field">
                            <label for="signin-login">Login*</label>
                            <input id="signin-login" type="text" name="login" placeholder="Enter your login">
                        </div>
                        <div class="input_field">
                            <label for="signin-password">Password*</label>
                            <input id="signin-password" type="password" name="password" placeholder="Enter your password">
                        </div>
                        <button type="submit" class="btn">Sign In</button>
                    </form>
                    <form id="signup" data-tab="1" method="post">
                        <div class="input_field">
                            <label for="signup-name">Name*</label>
                            <input id="signup-name" type="text" name="name" placeholder="Enter your name">
                        </div>
                        <div class="input_field">
                            <label for="signup-login">Login*</label>
                            <input id="signup-login" type="text" name="login" placeholder="Enter your login">
                        </div>
                        <div class="input_field">
                            <label for="signup-email">Email*</label>
                            <input id="signup-email" type="text" name="email" placeholder="Enter your email">
                        </div>
                        <div class="input_field">
                            <label for="signup-password">Password*</label>
                            <input id="signup-password" type="password" name="password" placeholder="Enter your password">
                        </div>
                        <div class="input_field">
                            <label for="signup-confirm-password">Confirm*</label>
                            <input id="signup-confirm-password" data-required="password" type="password" name="confirm" placeholder="Enter your confirm">
                        </div>
                        <button type="submit" class="btn">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </main>
</body>
</html>