<?php

echo '
	<noscript>
		<style>
			.noscript-message {
				position: absolute;
				top: 0;
				left: 0;
				right: 0;
				bottom: 0;
				display: flex;
				align-items: center;
				justify-content: center;
				text-align: center;
				line-height: 28px;
				background-color: var(--dark-2);
				font-size: 24px;
				font-weight: 400;
				z-index: 10000;
			}	
		</style>
		<h1 class="noscript-message">
			Please, allow Javascript in the browser settings<br>
			to make the page work
		</h1>
	</noscript>
';

?>